#+BLOG: blog.datalab.es
#+CATEGORY: periodismodatos, ddj
#+TAGS: 
#+DESCRIPTION: 
#+AUTHOR: Adolfo Antón Bravo
#+EMAIL: adolfo@medialab-prado.es
#+TITLE: Editors Lab 2018: Breaking News Contest
#+DATE: <2018-01-18 jue>
#+OPTIONS:  num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+TOC: headlines 2
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \addto\captionsenglish{\renewcommand{\contentsname}{{\'I}ndice}}
#+LATEX_HEADER: \renewcommand{\contentsname}{Índice}
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: linear
#+REVEAL_THEME: sky
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Herramientas de Scraping de PDF y Web.">
#+REVEAL_POSTAMBLE: <p> Creado por adolflow. </p>
#+REVEAL_PLUGINS: (highlight notes)
#+REVEAL_EXTRA_CSS: file:///home/flow/Documentos/software/reveal.js/css/reveal.css
#+REVEAL_ROOT: file:///home/flow/Documentos/software/reveal.js/
#+LATEX_HEADER: \maketitle
#+LATEX_HEADER: \tableofcontents

[[https://www.globaleditorsnetwork.org/][Global Editors Network]] (GEN) y [[http://www.elconfidencial.com][El Confidencial]], con el soporte de Google News Lab, celebran la edición de 2018
de /Editors Lab, Prototyping the future of News/ (laboratorio  sobre últimas noticias) . DataLab Madrid ha sido invitado a
participar los días 18 y 19 de enero en esta edición que tiene lugar en la [[https://www.google.es/maps/place/El%2BConfidencial/@40.4404264,-3.8556108,12z/data%3D!4m8!1m2!2m1!1sel%2Bconfidencial!3m4!1s0xd41864d791c73ad:0x1ecbe4498a665853!8m2!3d40.440813!4d-3.785099][redacción de El Confidencial]] para
experimentar con la temática de 2018: últimas noticas o /breaking news/.

* Intro
/Editors Lab/ 2018 reúne once equipos de los medios o entidades a la vanguardia de las tecnologías de la
información aplicadas al periodismo. La competición dura dos días y se pretende desarrollar un prototipo de un
producto periodístico innovador. Este año, el tema del hackathon serán * las últimas noticias*.

La red mundial de editores (GEN) agrupa a los medios más importantes del mundo, entre los que se encuentran
/El País/, /The Washington Post/, /The New York Times/, /The Guardian/, /The Times/ o /Le Monde/, entre otros
muchos. En 2015 la edición de /Editors Lab/ fue organizada por segunda vez por el diario /El País/, en cuya
redacción se desarrolló la competición, y contó con la colaboración de Medialab-Prado. En esa ocasión, el
equipo de lo conformaron Martín Nadal, Chema Blanco y Adolfo Antón Bravo, quienes desarrollaron una segunda
versión del proyecto [[http://mapas.muimota.net/][Mapas del descontento]] de Martín Nadal que fue iniciado durante la [[http://medialab-prado.es/article/tallervisualizar15proyectos][edición de 2015 de
Visualizar]]. En 2015 el equipo ganador, por segunda ocasión, fue el /Grupo Vocento/.

Con un parón en 2016, en 2017 volvió a celebrarse en España en la redacción de El Confidencial, siendo este
medio también el ganador. El equipo de Medialab-Prado fue seleccionado después de una convocatoria abierta y
lo compusieron Santiago Mota, astrochat y periodista.

Los equipos ganadores de cada edición regional participan en un hackatón internacional que se celebra durante
la cumbre de la /GEN/, que en 2018 se realiza en mayo en Lisboa.

#+CAPTION: Imagen de GEN de la edición del Editors Lab 2015 en Medialab-Prado. [[https://creativecommons.org/licenses/by-nc/2.0/][Licencia CC]]
#+ATTR_HTML: :alt Imagen de GEN de la edición del Editors Lab 2015 en Medialab-Prado. [[https://creativecommons.org/licenses/by-nc/2.0/][Licencia CC]] :title EditorsLab_2015
https://farm1.staticflickr.com/528/18488623448_0db1dfac00_z_d.jpg

* Breaking News Challenge: Resume

En 2018 Alejandro Zappala, María Poveda y Adolfo Antón Bravo han realizado un prototipo sobre cómo poner en
contexto de forma automática, aumentada y enriquecida una noticia cualquiera.

* The breaking news challenge

Breaking news always stretches reporters and editors, no matter the medium, because of the time constraints it
creates.

In online journalism, the pressure to move quickly is particularly intense and therefore the challenges to
excellence are great.

From the early days of journalism on the web in the 1990s, the capacity of the medium for speed created new
possibilities but also new expectations. In the past few yearse, the proliferation of independent blogs and
news sites, along withe the development of social media such as Twitter, has provided even greater capacity
for quick communication but also intensified what was already a brutal competitive battle in online news.

Breaking news is one of the key ethical battlegrounds in online journalism because it highlights the tensions
between the best traditions of journalism and the competitive realities of the new media world.

The battle we are facing in trying to report and edit quickly and accurately and to go beyond basic accuracy
to provide context and depth.

Draw on the perspectives of online journalists to talk about standards of excellence in breaking news and the
challenges to maintaining those standards.

Profile the daily challenges one online editor faces on the job as he juggles the responsabilities of breaking
news.

** History

Doing breaking news well is a longtime challenge for journalist across media.

On a daily basis you have to confide on people, process, technology, sources and the desire to always be
first.

Mistakes are nothing new in breaking news coverage, online journalism steps up the previous pressures on
journalists.

The newspaper front-page job is every time it is needed.

There is no cycle but a stream. The continuing acceleration of the news cycle -the timing of story
development, editing and presentation.

* Linked Data

Los Datos Enlazados, como parte de la Web Semántica, se basa en la aplicación de ciertos principios básicos y necesarios, que fomentarán el crecimiento de la Web, tanto a nivel de los documentos HTML (vista clásica de la Web), como a nivel de los datos expresados en RDF (vista de la Web Semántica).

- Usar URIs para identificar las cosas, entidades, abstracciones de distintos nombres que con lenguaje natural
  se refieren a un mismo recurso.así ofrecer una forma estandar y unívoca para refererirnos a cualquier recurso. 
- Usar URIs HTTP, para acceder.
- Ofrecer información sobre los recursos usando RDF, para aprovechar su potencia: triplas del tipo =Sujeto, Propiedad, Valor=
  (Sujeto, Predicado, Objeto)
- Incluir enlaces a otros URIs, para enlazar URIs.

Este grafo representa a distintos conjuntos de datos de diversos tipos, organizados mediante colores por
dominios. Estos conjuntos de datos están conectados entre sí de forma que componen la “Nube de Linked Data” o
“Nube de Datos Enlazados”. 

** Linked Data 2007

#+CAPTION: Visualización de las conexiones y densidad de fuentes Linked Data 
#+ATTR_HTML: :alt Visualización de las conexiones y densidad de fuentes Linked Data  :title Visualización de las conexiones y densidad de fuentes Linked Data 
http://lod-cloud.net/versions/2007-05-01/lod-cloud.png

** Linked Data 2017

#+CAPTION: Visualización de las conexiones y densidad de fuentes Linked Data 
#+ATTR_HTML: :alt Visualización de las conexiones y densidad de fuentes Linked Data  :title Visualización de las conexiones y densidad de fuentes Linked Data 
http://lod-cloud.net/versions/2017-08-22/lod1000x822.png

* Linked Data Sorces

** Newsrooms

- New York Times
- BBC: [[https://www.bbc.co.uk/music][BBC Music]], [[https://www.bbc.co.uk/programmes][BBC Programmes]], [[http://www.bbc.co.uk/nature/animals/][BBC Nature]], 
- The Guardian

** General 
- Wikipedia
- DBpedia
- Wikidata
- Music: [[https://musicbrainz.org/][MusicBrainz]], 

** Especializadas
- GLAM:  LAM (libraries, archives y museums)

#+CAPTION: Ubicación de la web semántica en el ciclo de vida de la adopción de tecnologías. Fuente: Adaptación de figura de Ivan Herman (2011), http://www.informationr.net/ir/18-1/paper570.html
#+ATTR_HTML: :alt Ubicación de la web semántica en el ciclo de vida de la adopción de tecnologías   :title Ubicación de la web semántica en el ciclo de vida de la adopción de tecnologías
http://www.informationr.net/ir/18-1/p570fig01.jpg

** APIs
- [[https://elpais.com/tag/listado/][El País]]

** WikiNews
#+CAPTION: Logo de WikiNews
#+ATTR_HTML: :alt Logo de WikiNews :title Logo de WikiNews
https://commons.wikimedia.org/wiki/File:Wikinews-logo.svg

Wikinews (en español, [[https://meta.wikimedia.org/wiki/Wikinews/es][Wikinoticias]]) es un proyecto que tiene como objetivo colaborar con la divulgación y el
resumen de artículos y noticias de actualidad, sobre todos los temas, desde un punto de vista neutral. Esta
página describe los objetivos del proyecto y cuenta con cinco requerimientos básicos para su
aplicación. Wikinews cuenta con varias ediciones en más de 20 idiomas. Para podernos ayudar intentaremos
partir de un conjunto de políticas en Meta, que cada comunidad Wikinews podrá emplear como base para el
desarrollo de políticas locales.

*** Fases de un artículo
Por lo tanto definimos como segundo requisito de Wikinews, el que un artículo deba experimentar por lo menos cuatro etapas:

1. Desarrollo del artículo, fase durante la cual una comunidad de voluntarios trabaja sobre el texto y los
   medios correspondientes.
2. Revisión final, fase durante la cual se comprueba neutralidad, estado de copyright, legalidad y legibilidad
   del artículo.
3. Publicación del artículo, fase en que el artículo se enlaza y se etiqueta oficialmente como
   "publicado". Las correcciones y actualizaciones pueden hacerse durante un determinado tiempo si se indican
   claramente junto al artículo.
4. Archivado, fase en la cual el artículo se encuentra congelado de manera permanente, para poder ser
   citado. Las correcciones y actualizaciones pueden ser aún enlazadas, pero el texto del artículo en sí no
   puede editarse.

*** Normas

- Asegurar exactitud y legalidad.
- Neutralidad.
- Verificabilidad.




** API REST

* Herramienta

** Base tecnológica
- Normas
- Consenso
- Información oficial

** Open Context
- Standards
- Software
- Geographic Reference System

** Desarrollo

- 

